# -*- coding: utf-8 -*-
"""Untitled0.ipynb
Automatically generated by Colaboratory.
Original file is located at
    https://colab.research.google.com/drive/1xlA3omMGzM5TC2xWzAegIk1fwKk9SOBm
"""

import tensorflow as tf

!pip install transformers[sentencepiece]

from transformers import TFAutoModelForSequenceClassification
model = TFAutoModelForSequenceClassification.from_pretrained("youscan/ukr-roberta-base", from_pt=True, num_labels=2)
model.load_weights("./drive/MyDrive/model_weights")

model.summary()

import numpy as np
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained("youscan/ukr-roberta-base")

text = "Ця потвора вкрала в неї капелюха"
text1="Я тебе кохаю, бо ти найкрасивіша у світі, і я завжди буду любити тільки тебе"
text2='Мені зовсім не подобається його поведінка в школі'
encoding = tokenizer(text, return_tensors="np", padding=True)['input_ids']
encoding1 = tokenizer(text1, return_tensors="np", padding=True)['input_ids']
encoding2 = tokenizer(text2, return_tensors="np", padding=True)['input_ids']

outputs = model.predict(encoding)
class_preds = np.argmax(outputs["logits"])
print(outputs)
print(class_preds)
